name: Start Tunnel Request

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  start:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Update control.json
        run: |
          cat > control.json <<EOF
          {
            "request": "start",
            "url": ""
          }
          EOF

      - name: Commit and Push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add control.json

          git diff --cached --quiet && exit 0

          git commit -m "Request tunnel start"

          git pull --rebase origin main
          git push origin HEAD:main
